In [1]:
import pandas as pd
import maps
import api

In [2]:
df = pd.read_csv('https://simplemaps.com/static/data/country-cities/pl/pl.csv')
df.head(n=20)

,city,lat,lng,country,iso2,admin_name,capital,population,population_proper
0,Warsaw,52.2167,21.0333,Poland,PL,Mazowieckie,primary,1790658.0,1790658.0
1,Kraków,50.0614,19.9372,Poland,PL,Małopolskie,admin,766739.0,766739.0
2,Łódź,51.7769,19.4547,Poland,PL,Łódzkie,admin,690422.0,690422.0
3,Wrocław,51.1100,17.0325,Poland,PL,Dolnośląskie,admin,638586.0,638586.0
4,Poznań,52.4000,16.9167,Poland,PL,Wielkopolskie,admin,533830.0,533830.0
5,Gdańsk,54.3667,18.6333,Poland,PL,Pomorskie,admin,464254.0,464254.0
6,Szczecin,53.4247,14.5553,Poland,PL,Zachodniopomorskie,admin,403833.0,403833.0
7,Bydgoszcz,53.1167,18.0000,Poland,PL,Kujawsko-Pomorskie,admin,346739.0,346739.0
8,Lublin,51.2333,22.5667,Poland,PL,Lubelskie,admin,339850.0,339850.0
9,Białystok,53.1167,23.1667,Poland,PL,Podlaskie,admin,297554.0,297554.0
10,Katowice,50.2500,19.0000,Poland,PL,Śląskie,admin,276499.0,276499.0
11,Gdynia,54.5189,18.5319,Poland,PL,Pomorskie,minor,247672.0,247672.0
12,Częstochowa,50.8096,19.1222,Poland,PL,Śląskie,minor,228179.0,228179.0
13,Radom,51.4036,21.1567,Poland,PL,Mazowieckie,minor,219703.0,219703.0
14,Toruń,53.0167,18.6167,Poland,PL,Kujawsko-Pomorskie,admin,201447.0,201447.0
15,Sosnowiec,50.3000,19.1667,Poland,PL,Śląskie,minor,199974.0,199974.0
16,Kielce,50.8725,20.6319,Poland,PL,Świętokrzyskie,admin,191605.0,191605.0
17,Rzeszów,50.0500,22.0000,Poland,PL,Podkarpackie,admin,182548.0,182548.0
18,Gliwice,50.3011,18.6498,Poland,PL,Śląskie,minor,179806.0,179806.0
19,Zabrze,50.3000,18.7833,Poland,PL,Śląskie,minor,174349.0,174349.0

In [3]:
df.dtypes

city                  object
lat                  float64
lng                  float64
country               object
iso2                  object
admin_name            object
capital               object
population           float64
population_proper    float64
dtype: object

In [4]:
df.isna().sum()

city                   0
lat                    0
lng                    0
country                0
iso2                   0
admin_name             0
capital                5
population           138
population_proper    138
dtype: int64

In [ ]:
# creating a draft map to see the spread of locations
m = maps.DraftMap()
m.draft_map(lat=df.lat, lon=df.lng)

In [ ]:
con = api.Connector()
results = con.fetch(lats = df['lat'], lons = df['lng'], cities = df['city'])

In [9]:
final = maps.FinalMap()
m = final.final_map(df, results)

In [10]:
m.save('map.html')